### ISSUE TITLE
Create wire-frames

### ISSUE THREAD

**Issue by Arubyt** [Arubyt/MusEx-The-Quest-#4]

**Comment by gmunatsi** [comment]
This involves the creation of a logo and the layout of the app.

**Comment by Arubyt** [comment]
![imag5427](https://cloud.githubusercontent.com/assets/26165446/25279583/402dbcf8-267d-11e7-8269-6c2eb169a697.jpg)

![imag5428](https://cloud.githubusercontent.com/assets/26165446/25279606/61563b12-267d-11e7-885a-7b44fb929e3b.jpg)

![imag5429](https://cloud.githubusercontent.com/assets/26165446/25279668/9987e8d2-267d-11e7-9769-3e64e48fd2ba.jpg)

![imag5430](https://cloud.githubusercontent.com/assets/26165446/25279702/b6ec067e-267d-11e7-9e97-f89c5e084cb4.jpg)

![imag5431](https://cloud.githubusercontent.com/assets/26165446/25279748/dd2b80c6-267d-11e7-87a9-9db8e3bac2d4.jpg)

![imag5433](https://cloud.githubusercontent.com/assets/26165446/25279825/21e13a26-267e-11e7-972c-472a09046b97.jpg)
